controllers:
    resource: ../src/Controller/
    type: attribute
# # message:
# #      path: /message
# #      controller: App\Controller\MessageController::message
# # nextpage:
# #      path: /
# #      controller: App\Controller\NextpageController::nextpage

