<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTxx3I5u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTxx3I5u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTxx3I5u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTxx3I5u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTxx3I5u\App_KernelDevDebugContainer([
    'container.build_hash' => 'Txx3I5u',
    'container.build_id' => '314fc386',
    'container.build_time' => 1664191030,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTxx3I5u');
