<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHZ4Yey9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHZ4Yey9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHZ4Yey9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHZ4Yey9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHZ4Yey9\App_KernelDevDebugContainer([
    'container.build_hash' => 'HZ4Yey9',
    'container.build_id' => '603be883',
    'container.build_time' => 1663154738,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHZ4Yey9');
