<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTS6ktA1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTS6ktA1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTS6ktA1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTS6ktA1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTS6ktA1\App_KernelDevDebugContainer([
    'container.build_hash' => 'TS6ktA1',
    'container.build_id' => '0bb39202',
    'container.build_time' => 1663849099,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTS6ktA1');
