<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'hello' => [[], ['_controller' => 'App\\Controller\\MessageController::greetings'], [], [['text', '/']], [], [], []],
    'examplepage' => [['slug'], ['slug' => 1, '_controller' => 'App\\Controller\\MessageController::slugExample'], ['slug' => '\\d+'], [['variable', '/', '\\d+', 'slug', true], ['text', '/nextpage']], [], [], []],
    'requirementpage' => [['slug'], ['_controller' => 'App\\Controller\\MessageController::requirement'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/nextpage']], [], [], []],
    'twigpage' => [[], ['_controller' => 'App\\Controller\\MessageController::twigexample'], [], [['text', '/twigexample']], [], [], []],
];
